import pytest
from app.movies_app import create_app
from app.infrastructure.extensions import db

@pytest.fixture
def app():
    app = create_app()

    app.config.update({
        "TESTING": True,
        "SQLALCHEMY_DATABASE_URI": "sqlite:///:memory:",
        "SQLALCHEMY_TRACK_MODIFICATIONS": False
    })

    with app.app_context():
        db.create_all()
        yield app
        db.session.remove()
        db.drop_all()

    return app

@pytest.fixture
def client(app):
    return app.test_client()

@pytest.fixture
def runner(app):
    return app.test_cli_runner()

@pytest.fixture
def base_url():
    return "http://127.0.0.1:8000"

mock_response_get_popular_movies = [
    {
        "adult": False,
        "backdrop_path": "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
        "genre_ids": [27, 18, 878],
        "id": 933260,
        "original_language": "en",
        "original_title": "The Substance",
        "overview": "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
        "popularity": 4181.925,
        "poster_path": "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
        "release_date": "2024-09-07",
        "title": "The Substance",
        "video": False,
        "vote_average": 7.4,
        "vote_count": 466,
    },
    {
        "adult": False,
        "backdrop_path": "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
        "genre_ids": [28, 35, 878],
        "id": 533535,
        "original_language": "en",
        "original_title": "Deadpool & Wolverine",
        "overview": "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
        "popularity": 3503.165,
        "poster_path": "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        "release_date": "2024-07-24",
        "title": "Deadpool & Wolverine",
        "video": False,
        "vote_average": 7.714,
        "vote_count": 4452,
    },
    {
        "adult": False,
        "backdrop_path": "/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg",
        "genre_ids": [35, 14, 27],
        "id": 917496,
        "original_language": "en",
        "original_title": "Beetlejuice Beetlejuice",
        "overview": "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Betelgeuse, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
        "popularity": 2699.55,
        "poster_path": "/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg",
        "release_date": "2024-09-04",
        "title": "Beetlejuice Beetlejuice",
        "video": False,
        "vote_average": 7.2,
        "vote_count": 1271,
    },
    {
        "adult": False,
        "backdrop_path": "/3m0j3hCS8kMAaP9El6Vy5Lqnyft.jpg",
        "genre_ids": [878, 53, 18, 27],
        "id": 1125510,
        "original_language": "es",
        "original_title": "El hoyo 2",
        "overview": "After a mysterious leader imposes his law in a brutal system of vertical cells, a new arrival battles against a dubious food distribution method.",
        "popularity": 2554.356,
        "poster_path": "/izuzUb0sDokqp9o8utVfsrSJuy5.jpg",
        "release_date": "2024-09-27",
        "title": "The Platform 2",
        "video": False,
        "vote_average": 5.696,
        "vote_count": 529,
    },
    {
        "adult": False,
        "backdrop_path": "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
        "genre_ids": [27, 53],
        "id": 1034541,
        "original_language": "en",
        "original_title": "Terrifier 3",
        "overview": "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
        "popularity": 1847.201,
        "poster_path": "/l1175hgL5DoXnqeZQCcU3eZIdhX.jpg",
        "release_date": "2024-10-09",
        "title": "Terrifier 3",
        "video": False,
        "vote_average": 7.1,
        "vote_count": 55,
    },
    {
        "adult": False,
        "backdrop_path": "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
        "genre_ids": [16, 10751, 35, 28],
        "id": 519182,
        "original_language": "en",
        "original_title": "Despicable Me 4",
        "overview": "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
        "popularity": 1691.373,
        "poster_path": "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
        "release_date": "2024-06-20",
        "title": "Despicable Me 4",
        "video": False,
        "vote_average": 7.1,
        "vote_count": 1975,
    },
    {
        "adult": False,
        "backdrop_path": "/v9acaWVVFdZT5yAU7J2QjwfhXyD.jpg",
        "genre_ids": [16, 878, 10751],
        "id": 1184918,
        "original_language": "en",
        "original_title": "The Wild Robot",
        "overview": "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
        "popularity": 1630.358,
        "poster_path": "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
        "release_date": "2024-09-12",
        "title": "The Wild Robot",
        "video": False,
        "vote_average": 8.3,
        "vote_count": 275,
    },
    {
        "adult": False,
        "backdrop_path": "/g1z1ZvYKcmk9EnVOTYXR6vkNjkZ.jpg",
        "genre_ids": [14, 27, 28],
        "id": 1087822,
        "original_language": "en",
        "original_title": "Hellboy: The Crooked Man",
        "overview": "Hellboy and a rookie BPRD agent get stranded in 1950s rural Appalachia. There, they discover a small community haunted by witches, led by a local devil with a troubling connection to Hellboy's past: the Crooked Man.",
        "popularity": 1337.465,
        "poster_path": "/iz2GabtToVB05gLTVSH7ZvFtsMM.jpg",
        "release_date": "2024-08-29",
        "title": "Hellboy: The Crooked Man",
        "video": False,
        "vote_average": 4.8,
        "vote_count": 110,
    },
    {
        "adult": False,
        "backdrop_path": "/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg",
        "genre_ids": [16, 10751, 12, 35, 18],
        "id": 1022789,
        "original_language": "en",
        "original_title": "Inside Out 2",
        "overview": "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
        "popularity": 1306.455,
        "poster_path": "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        "release_date": "2024-06-11",
        "title": "Inside Out 2",
        "video": False,
        "vote_average": 7.632,
        "vote_count": 4317,
    },
    {
        "adult": False,
        "backdrop_path": "/hPIWQT70wQK6akqfLXByEvr62u0.jpg",
        "genre_ids": [28, 53, 27, 878],
        "id": 726139,
        "original_language": "ko",
        "original_title": "탈출: 프로젝트 사일런스",
        "overview": 'Due to sudden deteriorating weather conditions, visibility on the Airport Bridge is severely impaired, leaving people stranded and at risk of the bridge collapsing due to a series of chain collisions and explosions. Amidst the chaos, the canine subjects "Echo" from the military experiment "Project Silence," who were being transported in secret, break free, and all human survivors become targets of relentless attacks.',
        "popularity": 1281.646,
        "poster_path": "/fttoFfKikQMwIoV3UVvlCvBhbUw.jpg",
        "release_date": "2024-07-11",
        "title": "Project Silence",
        "video": False,
        "vote_average": 7.08,
        "vote_count": 168,
    },
    {
        "adult": False,
        "backdrop_path": "/tCKWksaQI8XkAQLVou0AlGab5S6.jpg",
        "genre_ids": [28, 878],
        "id": 1144962,
        "original_language": "en",
        "original_title": "Transmorphers: Mech Beasts",
        "overview": "20 years after the events of Transmorphers, a newer, more advanced species of alien robot descends on a rebuilt Earth, threatening once again to destroy the planet.",
        "popularity": 1180.91,
        "poster_path": "/oqhaffnQqSzdLrYAQA5W4IdAoCX.jpg",
        "release_date": "2023-06-09",
        "title": "Transmorphers: Mech Beasts",
        "video": False,
        "vote_average": 4.9,
        "vote_count": 23,
    },
    {
        "adult": False,
        "backdrop_path": "/uVWlwJebxX0M3axXAUrryJ6w9cQ.jpg",
        "genre_ids": [28, 35, 80],
        "id": 507241,
        "original_language": "en",
        "original_title": "The Killer's Game",
        "overview": "When top hitman Joe Flood is diagnosed with a terminal illness, he decides to take matters into his own hands – by taking a hit out on himself. But when the very hitmen he hired also target his ex-girlfriend, he must fend off an army of assassin colleagues and win back the love of his life before it's too late.",
        "popularity": 1067.231,
        "poster_path": "/4bKlTeOUr5AKrLky8mwWvlQqyVd.jpg",
        "release_date": "2024-09-12",
        "title": "The Killer's Game",
        "video": False,
        "vote_average": 6.212,
        "vote_count": 59,
    },
    {
        "adult": False,
        "backdrop_path": "/Asg2UUwipAdE87MxtJy7SQo08XI.jpg",
        "genre_ids": [28, 14, 27],
        "id": 957452,
        "original_language": "en",
        "original_title": "The Crow",
        "overview": "Soulmates Eric and Shelly are brutally murdered when the demons of her dark past catch up with them. Given the chance to save his true love by sacrificing himself, Eric sets out to seek merciless revenge on their killers, traversing the worlds of the living and the dead to put the wrong things right.",
        "popularity": 1003.957,
        "poster_path": "/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg",
        "release_date": "2024-08-21",
        "title": "The Crow",
        "video": False,
        "vote_average": 5.724,
        "vote_count": 603,
    },
    {
        "adult": False,
        "backdrop_path": "/vGaBqgY8YRzQVUbBMPnd5SmYvL7.jpg",
        "genre_ids": [16, 35],
        "id": 1329336,
        "original_language": "en",
        "original_title": "The Bad Guys: Haunted Heist",
        "overview": "The crafty Bad Guys crew embarks on a high-stakes Halloween heist to swipe a priceless amulet from a spooky mansion. What could go wrong?",
        "popularity": 944.292,
        "poster_path": "/oEJC05CqPugMxC4rFu9r6r6vg6m.jpg",
        "release_date": "2024-10-02",
        "title": "The Bad Guys: Haunted Heist",
        "video": False,
        "vote_average": 7.4,
        "vote_count": 46,
    },
    {
        "adult": False,
        "backdrop_path": "/eXQ8O0ykuEB8dUJhq2WJll4vXmA.jpg",
        "genre_ids": [28, 35, 80],
        "id": 1210794,
        "original_language": "sv",
        "original_title": "Strul",
        "overview": "Wrongfully convicted of murder, a clumsy electronics salesman faces police corruption and criminal conspiracies in an attempt to prove his innocence.",
        "popularity": 917.854,
        "poster_path": "/ildbg7ho14EHbt1fZWAkgqIyPqy.jpg",
        "release_date": "2024-10-02",
        "title": "Trouble",
        "video": False,
        "vote_average": 7.1,
        "vote_count": 77,
    },
    {
        "adult": False,
        "backdrop_path": "/6n8x85cljOfJkUvPDc7tTmGPv7F.jpg",
        "genre_ids": [28, 27, 53],
        "id": 1029235,
        "original_language": "en",
        "original_title": "Azrael",
        "overview": "In a world where no one speaks, a devout female hunts down a young woman who has escaped her imprisonment. Recaptured by its ruthless leaders, Azrael is due to be sacrificed to pacify an ancient evil deep within the surrounding wilderness.",
        "popularity": 900.011,
        "poster_path": "/qpdFKDvJS7oLKTcBLXOaMwUESbs.jpg",
        "release_date": "2024-09-27",
        "title": "Azrael",
        "video": False,
        "vote_average": 5.6,
        "vote_count": 39,
    },
    {
        "adult": False,
        "backdrop_path": "/1fL2S8LKxCVE9KoPRBXeagmBtex.jpg",
        "genre_ids": [27, 53],
        "id": 1114513,
        "original_language": "en",
        "original_title": "Speak No Evil",
        "overview": "When an American family is invited to spend the weekend at the idyllic country estate of a charming British family they befriended on vacation, what begins as a dream holiday soon warps into a snarled psychological nightmare.",
        "popularity": 896.738,
        "poster_path": "/fDtkrO2OAF8LKQTdzYmu1Y7lCLB.jpg",
        "release_date": "2024-09-11",
        "title": "Speak No Evil",
        "video": False,
        "vote_average": 7.352,
        "vote_count": 655,
    },
    {
        "adult": False,
        "backdrop_path": "/iYqSQaWDttQIQzsxg9xHyg0bttG.jpg",
        "genre_ids": [878, 27, 28],
        "id": 945961,
        "original_language": "en",
        "original_title": "Alien: Romulus",
        "overview": "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
        "popularity": 845.919,
        "poster_path": "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
        "release_date": "2024-08-13",
        "title": "Alien: Romulus",
        "video": False,
        "vote_average": 7.2,
        "vote_count": 1285,
    },
    {
        "adult": False,
        "backdrop_path": "/cRdA9xjHBbobw4LJFsQ3j1CgpVq.jpg",
        "genre_ids": [27, 53],
        "id": 663712,
        "original_language": "en",
        "original_title": "Terrifier 2",
        "overview": "A year after the Miles County massacre, Art the Clown is resurrected by a sinister entity. Art returns home, where he must hunt down and destroy teenage Sienna and her younger brother Jonathan on Halloween. As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",
        "popularity": 811.084,
        "poster_path": "/8gLhu8UFPZfH2Hv11JhTZkb9CVl.jpg",
        "release_date": "2022-10-06",
        "title": "Terrifier 2",
        "video": False,
        "vote_average": 6.779,
        "vote_count": 1812,
    },
    {
        "adult": False,
        "backdrop_path": "/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg",
        "genre_ids": [28, 80, 53, 35],
        "id": 573435,
        "original_language": "en",
        "original_title": "Bad Boys: Ride or Die",
        "overview": "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
        "popularity": 798.865,
        "poster_path": "/oGythE98MYleE6mZlGs5oBGkux1.jpg",
        "release_date": "2024-06-05",
        "title": "Bad Boys: Ride or Die",
        "video": False,
        "vote_average": 7.516,
        "vote_count": 2174,
    },
]
